export { default as ChildrenIcon } from './children.svg';
export { default as DesertsIcon } from './deserts.svg';
export { default as DrinksIcon } from './drinks.svg';
export { default as FirstDishIcon } from './first dish.svg';
export { default as GrillIcon } from './grill.svg';
export { default as HealthyIcon } from './healthy.svg';
export { default as NationalIcon } from './national.svg';
export { default as PreparationsIcon } from './preparations.svg';
export { default as SalatIcon } from './salat.svg';
export { default as SauceIcon } from './sauce.svg';
export { default as SecondDishIcon } from './second dish.svg';
export { default as SnakesIcon } from './snakes.svg';
export { default as VeganIcon } from './vegan.svg';
